[package]
name = "meldable_heaps"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
divan = "0.1.14"
mimalloc = "0.1.43"
rand = { version = "0.8.5", features = ["small_rng"] }

[[bench]]
name = "push_pop"
harness = false
